# Generated by Django 5.0.2 on 2024-05-14 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_alter_question_question'),
        ('UserApp', '0004_userinfo_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_taken', models.DateTimeField(auto_now_add=True)),
                ('duration_minutes', models.IntegerField(default=0, verbose_name='Duration (minutes)')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.userinfo')),
            ],
            options={
                'db_table': 'Test',
            },
        ),
    ]
